# Build settings
markdown: kramdown
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: Dev Knights
description: Blogging about Software Engineering
timezone: America/Mexico_City
# email: contact@devknights.com
# blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
# cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

paginate: 5

url: "https://dev-knights.github.io" # the base hostname & protocol for your site
baseurl: ""

#used to display twitter cards
twitter_handle: '@arandilopez'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-52471938-4

exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "Rakefile", "THEME-LICENSE", "vendor"]
