# Build settings
markdown: kramdown
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: Dev Knights
description: > # this means to ignore newlines until "email:"
  Blogging about Software Engineering
timezone: America/Mexico_City
# email: contact@devknights.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
# cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

paginate: 5

url: "https://dev-knights.github.io" # the base hostname & protocol for your site
baseurl: ""

#used to display twitter cards
twitter_handle: '@arandilopez'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-52471938-4

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/devknights
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "Rakefile", "THEME-LICENSE"]
  # - icon:	facebook
  #   # url:	https://facebook.com/???
  #   # desc: Connect with me facebook
  #   share_url: https://www.facebook.com/sharer/sharer.php?app_id=229963537383921&amp;display=popup
  #   share_link: "&amp;u="

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
